### PR TITLE
Improve macro

### PR DESCRIPTION
**Pull request by chuxinh**
## What's change
- Use `qualify` to simplify macro `dedupe_utils`
- Update the jinja sql styles to the dbt style guide for both `dedupe_utils` and `incremental_utils`

## Testing
```
dbt run --select core/blocks.sql
Running with dbt=0.21.1
Found 3 models, 16 tests, 0 snapshots, 0 analyses, 175 macros, 0 operations, 0 seed files, 2 sources, 0 exposures
The selection criterion 'core/blocks.sql' does not match any nodes

WARNING: Nothing to do. Try checking your model configs and model specification args
root@ae102a794681:/harmony# dbt run --select core.blocks
Running with dbt=0.21.1
Found 3 models, 16 tests, 0 snapshots, 0 analyses, 175 macros, 0 operations, 0 seed files, 2 sources, 0 exposures

00:16:23 | Concurrency: 4 threads (target='dev')
00:16:23 | 
00:16:23 | 1 of 1 START incremental model DEV.blocks............................ [RUN]
00:16:34 | 1 of 1 OK created incremental model DEV.blocks....................... [SUCCESS 1 in 11.00s]
00:16:34 | 
00:16:34 | Finished running 1 incremental model in 17.90s.

Completed successfully

Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

### CODE REVIEW

**Comment by jfmyers** [comment]
This looks great!

Qualify greatly simplifies the logic. I wonder if there is a performance improvement there too.

I have an idea for an improvement on the `incremental_utils` macro. 

What do you think about removing the `WHERE` clause? 

I'm thinking about situations where we might want to use this macro in conjunction with other conditions on the query and the `WHERE` clause already exists. 

For example, the model code would be something like this if we updated the macro as I'm describing:
```
SELECT 
    ...fields
FROM <some table>
WHERE {{ incremental_load_filter("block_timestamp") }}
```

**Comment by drakedanner** [comment]
First PR! Nice!

**Comment by chuxinh** [comment]
> This looks great!
> 
> Qualify greatly simplifies the logic. I wonder if there is a performance improvement there too.
> 
> I have an idea for an improvement on the `incremental_utils` macro.
> 
> What do you think about removing the `WHERE` clause?
> 
> I'm thinking about situations where we might want to use this macro in conjunction with other conditions on the query and the `WHERE` clause already exists.
> 
> For example, the model code would be something like this if we updated the macro as I'm describing:
> 
> ```
> SELECT 
>     ...fields
> FROM <some table>
> WHERE {{ incremental_load_filter("block_timestamp") }}
> ```

yea that's making it more flexible. i will update it!

**Comment by chuxinh** [comment]
@jfmyers i just realised additional things we need to add to the `incremental_utils` is the 
```
{% if is_incremental() %}
... fields
{% endif %}
```
I ran into errors if i drop and try rebuilding the table in dev.
```
dbt run --full-refresh --select core.blocks
Running with dbt=0.21.1
Found 3 models, 16 tests, 0 snapshots, 0 analyses, 175 macros, 0 operations, 0 seed files, 2 sources, 0 exposures

12:01:49 | Concurrency: 4 threads (target='dev')
12:01:49 | 
12:01:49 | 1 of 1 START incremental model DEV.blocks............................ [RUN]
12:01:52 | 1 of 1 ERROR creating incremental model DEV.blocks................... [ERROR in 3.14s]
12:01:52 | 
12:01:52 | Finished running 1 incremental model in 9.67s.

Completed with 1 error and 0 warnings:

Database Error in model blocks (models/core/blocks.sql)
  002003 (42S02): SQL compilation error:
  Object 'HARMONY.DEV.BLOCKS' does not exist or not authorized.
  compiled SQL at target/run/harmony/models/core/blocks.sql

Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1

```
I guess we can either have the `is_incremental` part in the macro, but we also need to have else when it's not incremental and pull the earliest timestamp from. something like which may seem unnecessarily complicated or we just hard code some date like 1900-01-01 
```
{% macro incremental_load_filter(time_col, <timestamp>, <table>) -%}
    -- dbt makes it easy to query your target table by using the "{{ this }}" variable.
    {% if is_incremental() %}
      select max( {{ time_col }} ) from {{ this }}
    -- if full refresh, use min timestamp of the 
    {%- else -%}
      select min(<timestamp>) from {{ <some source table> }}
    {% endif %}
{%- endmacro %}
```
alternatively we can keep it the same but just need to add `is_incremental` to all the incremental tables. 
keen to hear your thoughts

**Comment by jfmyers** [comment]
Good point on including the `is_incremental`! However, you shouldn't need the `else` clause. If it's running in full_refresh mode it will just not run the `is_incremental` block and pull the full history from the source table.

**Comment by chuxinh** [comment]
> Good point on including the `is_incremental`! However, you shouldn't need the `else` clause. If it's running in full_refresh mode it will just not run the `is_incremental` block and pull the full history from the source table.

Think I figured out a better way but the `else` is still necessary as we removed `where` from the macro. See examples below
from this run: https://zsniary-metricsdao.snowflakecomputing.com/console#/monitoring/queries/detail?queryId=01a110c8-0501-824e-0073-0203000241b6
image

So I added else true so it does nothing but the where condition can still run: https://zsniary-metricsdao.snowflakecomputing.com/console#/monitoring/queries/detail?queryId=01a110c8-0501-824e-0073-02030002419e
image

Let me know if you're happy with this!

**Comment by jfmyers** [comment]
Very clever. Looks good to me!

**Review by jfmyers — APPROVED** [review]

**Pull request merged**
